import { Sprint, User, LeaderboardEntry, AiEvaluation, SettlementSummary } from "@/types";

export const MOCK_CURRENT_USER: User = {
  id: "usr_alex_01",
  githubUsername: "alexdev",
  name: "Demo Builder",
  avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=256&q=80",
  role: "VERIFIED_CREATOR",
  rank: "BRONZE",
  totalEarnedNgn: 0,
  sprintsCompleted: 0,
  currentStreak: 0,
  longestStreak: 0,
  successRate: 0,
  joinedAt: "2026-01-15T00:00:00.000Z",
  isVerifiedCreator: true,
  creatorVerificationStatus: "APPROVED",
};

export const MOCK_SPRINTS: Sprint[] = [
  {
    id: "spr_react_01",
    title: "React Landing Page 48h Sprint",
    slug: "react-landing-page-sprint",
    description: "Build a high-converting, fully responsive React landing page featuring hero section, interactive pricing table, feature list, and working contact form.",
    category: "FRONTEND",
    commitmentNgn: 5000,
    totalSlots: 20,
    filledSlots: 16,
    durationHours: 48,
    status: "ACTIVE",
    startTime: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
    endTime: new Date(Date.now() + 36 * 3600 * 1000).toISOString(),
    totalPoolNgn: 100000,
    passCount: 0,
    failCount: 0,
    tags: ["React", "Tailwind CSS", "Frontend"],
    creatorName: "Alex Rivera",
    isFeatured: true,
    definitionOfDone: [
      { id: "dod_1", title: "Hero Section", description: "Hero with high-impact title, visual demo/image, and CTA button", category: "FRONTEND", isRequired: true },
      { id: "dod_2", title: "Features Grid", description: "At least 3 feature cards with crisp icons & responsive layout", category: "FRONTEND", isRequired: true },
      { id: "dod_3", title: "Pricing Table", description: "Interactive pricing tier table with toggle or highlighted plan", category: "FRONTEND", isRequired: true },
      { id: "dod_4", title: "Contact Form", description: "Interactive contact/lead capture form with input validation", category: "FRONTEND", isRequired: true },
      { id: "dod_5", title: "Mobile Responsive", description: "Clean viewport layout at 375px mobile breakpoint without horizontal scroll", category: "CODE_QUALITY", isRequired: true },
      { id: "dod_6", title: "Live Deployment", description: "Deployed on Vercel, Netlify, or Cloudflare Pages with active URL", category: "DEPLOYMENT", isRequired: true },
    ],
  },
  {
    id: "spr_mobile_02",
    title: "React Native Expo Mobile Wallet Sprint",
    slug: "react-native-expo-wallet",
    description: "Develop a mobile wallet app in React Native / Expo with offline biometric lock screen, transaction history, and QR transfer flow.",
    category: "MOBILE",
    commitmentNgn: 7500,
    totalSlots: 15,
    filledSlots: 10,
    durationHours: 48,
    status: "ACTIVE",
    startTime: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
    endTime: new Date(Date.now() + 42 * 3600 * 1000).toISOString(),
    totalPoolNgn: 112500,
    passCount: 0,
    failCount: 0,
    tags: ["React Native", "Expo", "TypeScript", "Mobile"],
    creatorName: "Sarah Chen",
    isFeatured: true,
    definitionOfDone: [
      { id: "dod_201", title: "Expo App Manifest", description: "Valid app.json manifest with splash screen & icon assets", category: "FRONTEND", isRequired: true },
      { id: "dod_202", title: "QR Code Scanner", description: "Functional camera component reading payment payload strings", category: "FRONTEND", isRequired: true },
      { id: "dod_203", title: "Live Web/Mobile Build", description: "Active Expo Snack URL or GitHub release build APK/Web demo", category: "DEPLOYMENT", isRequired: true },
    ],
  },
  {
    id: "spr_ai_model_03",
    title: "RAG Pipeline & LLM Agent API",
    slug: "rag-llm-agent-api",
    description: "Architect a RAG search vector backend with FastAPI, Qdrant, and OpenAI embeddings returning structured JSON reasoning.",
    category: "AI_ENGINEERING",
    commitmentNgn: 15000,
    totalSlots: 10,
    filledSlots: 8,
    durationHours: 72,
    status: "ACTIVE",
    startTime: new Date(Date.now() - 20 * 3600 * 1000).toISOString(),
    endTime: new Date(Date.now() + 52 * 3600 * 1000).toISOString(),
    totalPoolNgn: 150000,
    passCount: 0,
    failCount: 0,
    tags: ["AI", "Python", "FastAPI", "RAG"],
    creatorName: "Kofi Mensah",
    isFeatured: false,
    definitionOfDone: [
      { id: "dod_301", title: "Vector Embeddings", description: "Qdrant/Pinecone vector index integration", category: "BACKEND", isRequired: true },
      { id: "dod_302", title: "FastAPI Endpoint", description: "REST API endpoint returning latency < 800ms", category: "BACKEND", isRequired: true },
    ],
  },
];

export const MOCK_LEADERBOARD: LeaderboardEntry[] = [
  {
    rankPosition: 1,
    user: {
      id: "usr_1",
      githubUsername: "sarah_code",
      name: "Sarah Chen",
      avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=256&q=80",
      role: "VERIFIED_CREATOR",
      rank: "ELITE",
      totalEarnedNgn: 142500,
      sprintsCompleted: 18,
      currentStreak: 14,
      longestStreak: 14,
      successRate: 100,
      joinedAt: "2026-01-01T00:00:00.000Z",
      isVerifiedCreator: true,
      creatorVerificationStatus: "APPROVED",
    },
    totalEarnedNgn: 142500,
    successRate: 100,
    streak: 14,
    completedSprintsCount: 18,
  },
  {
    rankPosition: 2,
    user: {
      id: "usr_2",
      githubUsername: "dev_kofi",
      name: "Kofi Mensah",
      avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=256&q=80",
      role: "BUILDER",
      rank: "ELITE",
      totalEarnedNgn: 118000,
      sprintsCompleted: 15,
      currentStreak: 11,
      longestStreak: 12,
      successRate: 96,
      joinedAt: "2026-01-05T00:00:00.000Z",
      isVerifiedCreator: false,
      creatorVerificationStatus: "NONE",
    },
    totalEarnedNgn: 118000,
    successRate: 96,
    streak: 11,
    completedSprintsCount: 15,
  },
  {
    rankPosition: 3,
    user: MOCK_CURRENT_USER,
    totalEarnedNgn: 87500,
    successRate: 94,
    streak: 7,
    completedSprintsCount: 12,
  },
];

export const MOCK_AI_EVALUATION_PASS: AiEvaluation = {
  id: "eval_99",
  submissionId: "sub_100",
  result: "PASS",
  confidenceScore: 97,
  reasoning: [
    { itemId: "dod_1", itemTitle: "Hero Section", isPassed: true, details: "Detected Hero element with headline 'ShipR' and primary CTA button", confidence: 99 },
    { itemId: "dod_2", itemTitle: "Features Grid", isPassed: true, details: "Found grid container with 4 feature cards and inline SVG iconography", confidence: 96 },
    { itemId: "dod_3", itemTitle: "Pricing Table", isPassed: true, details: "Pricing table detected with Monthly/Yearly toggle and highlight tier", confidence: 95 },
    { itemId: "dod_4", itemTitle: "Contact Form", isPassed: true, details: "Functional form with email input validation and submit handler", confidence: 98 },
    { itemId: "dod_5", itemTitle: "Mobile Responsive", isPassed: true, details: "No overflow-x detected at 375px viewport breakpoint", confidence: 97 },
    { itemId: "dod_6", itemTitle: "Live Deployment", isPassed: true, details: "Active Vercel SSL deployment returning 200 OK status code", confidence: 100 },
  ],
  suggestions: [
    "Consider adding meta tags for Twitter Card social sharing.",
    "Lighthouse performance score is 92/100; optimize image webp formats for 98+.",
  ],
  evaluatedAt: new Date().toISOString(),
};

export const MOCK_SETTLEMENT_SUMMARY: SettlementSummary = {
  sprintId: "spr_react_01",
  sprintTitle: "React Landing Page 48h Sprint",
  totalPoolNgn: 100000,
  totalParticipants: 20,
  passCount: 16,
  failCount: 4,
  initialStakeRefundNgn: 5000,
  redistributedBonusNgn: 1250,
  totalReturnPerPassNgn: 6250,
  settledAt: new Date().toISOString(),
};
